### ISSUE TITLE
Add parameter to use the node_modules directory as source for the sBOM

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/npm-dependencies-extractor#16]
We feel that sometimes it's hard to figure out what modules are used in the code.

In the `package-lock.json` file there might be some `optional` packages, f.e. `fsevent` has `abbrev` as `optional` dependency.

Talking to a frontend expert we've figured out, that we might use the `node_modules` directory to determine the sBOM.

Maybe we can add an argument to use the `node_module` as input. Suggestion argument: `useNodeModulesDirectoryOnly`

**Comment by sandacontiume** [comment]
Closing this issue, as we created a solution independent of npm (applicable for yarn e.g.) that reads dependencies from an input node_modules folder:

https://github.com/philips-software/node-modules-dependencies-extractor
